// Objective-C API for talking to mobile-sdk Go package.
//   gobind -lang=objc mobile-sdk
//
// File is generated by gobind. Do not edit.

#ifndef __GoLogpackermobilesdk_H__
#define __GoLogpackermobilesdk_H__

#include <Foundation/Foundation.h>

@class GoLogpackermobilesdkClient;
@class GoLogpackermobilesdkMessage;
@class GoLogpackermobilesdkResult;

@interface GoLogpackermobilesdkClient : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)clusterURL;
- (void)setClusterURL:(NSString*)v;
- (NSString*)environment;
- (void)setEnvironment:(NSString*)v;
- (NSString*)agent;
- (void)setAgent:(NSString*)v;
- (GoLogpackermobilesdkMessage*)newMessage;
- (BOOL)send:(GoLogpackermobilesdkMessage*)msg ret0_:(GoLogpackermobilesdkResult**)ret0_ error:(NSError**)error;
@end

@interface GoLogpackermobilesdkMessage : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)message;
- (void)setMessage:(NSString*)v;
- (NSString*)source;
- (void)setSource:(NSString*)v;
- (int)logLevel;
- (void)setLogLevel:(int)v;
- (NSString*)userID;
- (void)setUserID:(NSString*)v;
- (NSString*)userName;
- (void)setUserName:(NSString*)v;
- (NSString*)tagName;
- (void)setTagName:(NSString*)v;
@end

@interface GoLogpackermobilesdkResult : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (int)code;
- (void)setCode:(int)v;
- (NSString*)error;
- (void)setError:(NSString*)v;
- (NSString*)id;
- (void)setID:(NSString*)v;
@end

@interface GoLogpackermobilesdk : NSObject 
+ (int) debugLogLevel;
+ (void) setDebugLogLevel:(int)v;

+ (int) errorLogLevel;
+ (void) setErrorLogLevel:(int)v;

+ (int) fatalLogLevel;
+ (void) setFatalLogLevel:(int)v;

+ (int) infoLogLevel;
+ (void) setInfoLogLevel:(int)v;

+ (int) noticeLogLevel;
+ (void) setNoticeLogLevel:(int)v;

+ (int) warnLogLevel;
+ (void) setWarnLogLevel:(int)v;

@end

FOUNDATION_EXPORT BOOL GoLogpackermobilesdkNewClient(NSString* clusterURL, NSString* environment, NSString* agent, GoLogpackermobilesdkClient** ret0_, NSError** error);

#endif
